### ISSUE TITLE
Stuck loading at "Downloading Journal Resources (3/10)"

### ISSUE THREAD

**Issue by GibsonRun** [kakaroto/R20Exporter#4] opened 2019-08-14 08:15 UTC
I've recently just downloaded the program, but after getting players and macros and such, it keeps stopping at "Stuck loading at "Downloading Journal Resources (3/10)" regardless of the amount of tabs I have open in chrome. Please help
![image](https://user-images.githubusercontent.com/54098920/63005261-06e72f80-be31-11e9-892f-1fa36e8af0ef.png)

**Comment by kakaroto** [comment] 2019-08-16 09:24
As discussed over Discord, it seems to have been fixed. If you can reliably reproduce it though (updated chrome and updated tampermonkey), then I'd be curious to see more on what the issue is, in case others get it too.
Closing this issue for now.

**Closed as completed by kakaroto** 2019-08-16 09:24 UTC
